return {
  ["workshop-1185229307"]={
    configuration_options={
      [""]="",
      DAMAGE_NUMBERS=true,
      DAMAGE_RESISTANCE=true,
      FRAME_PHASES=true,
      HORIZONTAL_OFFSET=0,
      NOEPIC=false,
      NONOEPIC=false,
      WETNESS_METER=false 
    },
    enabled=true 
  },
  ["workshop-1416161108"]={
    configuration_options={
      [""]=0,
      auto_add_to_list=false,
      auto_add_to_list_drop=false,
      auto_del_from_list=false,
      auto_del_from_list_drop=false,
      ban_time=1800,
      beebox_radius=false,
      builder_radius=false,
      building_burned_down=false,
      campfire_propagator=false,
      chester_protect=false,
      death_annonce=false,
      destruction_protection=false,
      destruction_punishment=false,
      destruction_vote=false,
      destruction_warning=false,
      dont_drop_when_died=false,
      egg_deploy=false,
      fire_protection=false,
      fire_punishment=false,
      fire_radius=false,
      fire_vote=false,
      fire_warning=false,
      firehound_propagator=false,
      flingomatic_improved=false,
      flingomatic_is_empty=false,
      glommer_protect=false,
      good_monsters=false,
      keybind_container=114,
      keybind_drop=106,
      keybind_friend=107,
      keybind_panel=108,
      language="En",
      lavae_protect=false,
      mob_broke=false,
      protect_wall=false,
      punishmentTip=false,
      read_radius=false,
      reeds_cactus=false,
      starcaller=false,
      test=false,
      vote_kick_time=3600,
      warnings_count=5 
    },
    enabled=true 
  },
  ["workshop-1595631294"]={
    configuration_options={
      BundleItems=false,
      ChangeSkin=true,
      Digornot=false,
      DragonflyChest=false,
      Icebox=true,
      SaltBox=false 
    },
    enabled=true 
  },
  ["workshop-1777789373"]={
    configuration_options={
      desolationspawner=false,
      plantregrowth=false,
      resourcerenewal=false,
      worldregrowth=false 
    },
    enabled=true 
  },
  ["workshop-1803285852"]={
    configuration_options={
      [""]=0,
      AutoPickupAsh=false,
      AutoPickupEnabled=false,
      AutoPickupPoop=false,
      AutoPickupRange=10,
      AutoPickupSeeds=false,
      AutoStackAsh=false,
      AutoStackEnabled=true,
      AutoStackMakeNewStackMainStack=true,
      AutoStackManuallyDroppedItems=false,
      AutoStackPoop=false,
      AutoStackRange=20,
      AutoStackSeeds=false,
      AutoStackTwiggyTreeTwigs=true,
      ManualDropStackRange=5,
      ManualStackAsh=false,
      ManualStackMakeNewStackMainStack=false,
      ManualStackPoop=false,
      ManualStackSeeds=false,
      PlayerMustHaveOneOfItemToAutoPickup=false,
      SmokePuffOnStacking=true,
      StackDuringPopulation=false 
    },
    enabled=true 
  },
  ["workshop-2074508776"]={
    configuration_options={ handmake=20, onlyclose=false, range=2.3 },
    enabled=true 
  },
  ["workshop-2326208689"]={
    configuration_options={
      FARM_PLANT_NEEDS_CTRL=true,
      FARM_PLANT_NEEDS_LANGUAGE="english",
      FARM_PLANT_NEEDS_TILEINFO=true 
    },
    enabled=true 
  },
  ["workshop-2373951100"]={
    configuration_options={
      [""]=0,
      SprinklerExtinguishHeatPercent=-1,
      SprinklerFuelBonusMultiplier=5,
      SprinklerMaxFuelTime=250,
      SprinklerProtectionDist=2.25,
      SprinklerProtectionTime=30,
      SprinklerRange=10,
      SprinklerRecipe="easy",
      SprinklerTempReduction=5,
      SprinklerWetPlayer="" 
    },
    enabled=true 
  },
  ["workshop-2477889104"]={
    configuration_options={
      BADGE_BG_BRIGHTNESS=60,
      BADGE_BG_OPACITY=100,
      COLOR_DOMESTICATION_DEFAULT="WHITE",
      COLOR_DOMESTICATION_ORNERY="ORANGE",
      COLOR_DOMESTICATION_PUDGY="PURPLE",
      COLOR_DOMESTICATION_RIDER="BLUE",
      COLOR_OBEDIENCE="RED",
      COLOR_TIMER="GREEN",
      ClientConfig=false,
      EnableSounds=false,
      GapModifier=0,
      HEALTH_BADGE_CLEAR_BG=false,
      HungerThreshold=10,
      OffsetX=0,
      OffsetXFine=0,
      OffsetXMult=1,
      OffsetY=0,
      OffsetYFine=0,
      OffsetYMult=1,
      SEPARATOR_BADGE_COLORS=1,
      SEPARATOR_BADGE_SETTINGS=1,
      SEPARATOR_GENERAL=1,
      SEPARATOR_POSITIONING_X=1,
      SEPARATOR_POSITIONING_Y=1,
      Scale=1,
      ShowByDefault=true,
      Theme="TheForge",
      ToggleKey="KEY_T" 
    },
    enabled=true 
  },
  ["workshop-2629184121"]={
    configuration_options={
      [""]=false,
      custom=false,
      delay=200,
      guano=true,
      halloween_ornament=true,
      halloweencandy=true,
      houndstooth=true,
      interval=5,
      poop=true,
      rottenegg=false,
      sketch=false,
      spoiled_food=true,
      stinger=true,
      winter_food=true,
      winter_ornament=true,
      winter_ornament_boss=true,
      winter_ornament_light=false 
    },
    enabled=true 
  },
  ["workshop-363112314"]={ configuration_options={  }, enabled=true },
  ["workshop-378160973"]={
    configuration_options={
      ENABLEPINGS=true,
      FIREOPTIONS=2,
      OVERRIDEMODE=false,
      SHAREMINIMAPPROGRESS=false,
      SHOWFIREICONS=true,
      SHOWPLAYERICONS=true,
      SHOWPLAYERSOPTIONS=2 
    },
    enabled=true 
  },
  ["workshop-462372013"]={ configuration_options={  }, enabled=true },
  ["workshop-466732225"]={ configuration_options={  }, enabled=true },
  ["workshop-501385076"]={
    configuration_options={
      quick_cook_on_fire=true,
      quick_harvest=true,
      quick_pick_cactus=true,
      quick_pick_plant_normal_ground=true 
    },
    enabled=true 
  },
  ["workshop-666155465"]={
    configuration_options={
      chestB=-1,
      chestG=-1,
      chestR=-1,
      display_hp=-1,
      food_estimation=-1,
      food_order=0,
      food_style=0,
      lang="auto",
      show_food_units=-1,
      show_uses=-1 
    },
    enabled=true 
  },
  ["workshop-697356989"]={
    configuration_options={
      enable_legacywarly=false,
      pondsurfer=false,
      surfboard_Difficulty="petals",
      walani_drying=0.3,
      walani_sanity=0.9,
      walani_speed=2,
      wilburpoopdmg=10,
      wilburrun="y",
      wilburthrow="y",
      woodlegs_luck=6,
      woodlegs_sanity=-0.08 
    },
    enabled=true 
  },
  
  ["workshop-850494968"]={
    configuration_options={ _POI_override=3, _PR_override=3, _REEDS_override=1, _TR_override=3 },
    enabled=true 
  },
  ["workshop-885426046"]={ configuration_options={  }, enabled=true } 
}